### ISSUE TITLE
corresponPixels function

### ISSUE THREAD

**Issue by ebenezergr** [davidstutz/extended-berkeley-segmentation-benchmark#1]
Hello, I got a problem with the function CorrespondPixels.
When I downloaded extended-berkeley-segmentation-benchmark this function was fully commented. I uncommented the lines 1, 28, 30, 32, 34, 36, 38 and added "function" at the beginning of the l 1 and "end" at the l 40.
But I can't modify anything else and don't really understand to what correspond the lines 28 to 38, and how to find match1.

**Comment by davidstutz** [comment]
No commented is completey right! You need to compile this function. In `correspondPixels.M` you will only find documentation. The source is in `source/correspondPixels.cc`. See the README how to compile the sources.

**Comment by ZubairKhan001** [comment]
Error: File: evaluation_bdry_image.m Line: 92 Column: 61
"groundTruth" previously appeared to be used as a function or command, conflicting with its use here as the name of a
variable.
A possible cause of this error is that you forgot to initialize the variable, or you have initialized it implicitly using
load or eval.
using in windows, unable ot compile the build.sh.

**Comment by davidstutz** [comment]
Are you sure that you don't use `groundTruth` as a name for something else? In this benchmark, it's solely used as variable name.

Also please give details on when this error occurs and why you can't build the benchmark. The above error message doe snot seem to stem from building, does it?

**Comment by ghost** [comment]
Hi, I also got this problem. 
A new function called groundTruth was introduced in MATLAB R2017a, check the link below. 
https://www.mathworks.com/help/vision/ref/groundtruth.html

So a simple to fix this problem is to (1) rename those 'groundTruth' cell in the groundTruth .mats to something like 'GT', and (2) replace the word 'groundTruth' to 'GT' in evaluation_bdry_image.m.

**Comment by davidstutz** [comment]
Ah OK, thanks for the info. I wasn't aware of this change. I will add a note to the README for this issue.

**Comment by JobinFrancisGithub** [comment]
Sir in the test_benchmarks.m,

imgDir = 'data/BSDS500/images';
gtDir = 'data/BSDS500/groundTruth';
inDir = 'data/BSDS500/superpixel_segs';
outDir = 'tests/test_7';
mkdir(outDir);
codes are there but I got tests\test_1 upto test_5. test_6], test_7 etc are I could not find . Pls give us the link to get the  same

**Comment by davidstutz** [comment]
These are the output directories as far as I remember. You do not need to create them in advance.

**Comment by JobinFrancisGithub** [comment]
I understood sir. it was my mistake. Thank you so much for your response.
