### ISSUE TITLE
Measures as a function of the superpixel count

### ISSUE THREAD

**Issue by HaziqRazali** [davidstutz/extended-berkeley-segmentation-benchmark#2]
Hey david, does the benchmark return the results wrt. superpixel count so I can plot measures like ASA as the number of superpixel varies ?

**Comment by davidstutz** [comment]
Well not directly. You need to run your algorithm several times for different numbers of superpixels. Then run the benchmark and then you can plot the curves.

The benchmark always takes a set of segmentations, it does not care how these segmentations were generated. Hope that answers your question.
