### ISSUE TITLE
compiling error in windows

### ISSUE THREAD

**Issue by ZubairKhan001** [davidstutz/extended-berkeley-segmentation-benchmark#4]
can we compile the code in windows or its for linux, i encountered some errors while compiling.

**Comment by davidstutz** [comment]
It was intended for Linux, but nothing prevents you from trying it with Windows. Without any error message, however, I can't help you get it working.

**Comment by ZubairKhan001** [comment]
i tried to compile the build.sh but it is missing sys/times.h file, please look into it. thanks. below is the error details.
Building with 'Microsoft Visual C++ 2015'.
cl /c /Zp8 /GR /W3 /EHs /nologo /MD /O2 /Oy- /DNDEBUG /DMATLAB_DEFAULT_RELEASE=R2017b  /DUSE_MEX_CMD   /D_CRT_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_DEPRECATE /D_SECURE_SCL=0   /DMATLAB_MEX_FILE -I"C:\Program Files\MATLAB\R2018b\extern\include" -I"C:\Program Files\MATLAB\R2018b\simulink\include" "D:\image-segmentation-codes\extended-berkeley-segmentation-benchmark\source\correspondPixels.cc" /FoC:\Users\Engineer\AppData\Local\Temp\mex_3811659388890865_24300\correspondPixels.obj
Error using mex
correspondPixels.cc
d:\image-segmentation-codes\extended-berkeley-segmentation-benchmark\source\csa.hh(18): fatal error C1083: Cannot open include file:
'sys/times.h': No such file or directory



Error in build (line 1)
mex -v CXXFLAGS="\$CXXFLAGS -O3 -DNOBLAS" correspondPixels.cc csa.cc kofn.cc match.cc Exception.cc Matrix.cc Random.cc String.cc
Timer.cc
 
»

**Comment by davidstutz** [comment]
Ok, seems like the original benchmark uses `sys/times.h` only in very few places. I suggest you remove the corresponding `Timer.hh` and `Timer.cc` files and their occurrences - as far as I can tell only in `match.cc` and `build.m` and try to build again.

**Comment by ZubairKhan001** [comment]
i was able to run it on linux thanks,

**Comment by ZubairKhan001** [comment]
i wanted to ask that in the data/BSDS500 folder/segs, the segmentation are stored in the cells are of the same segmentation algorithm or for different algorithms. appreciated.

**Comment by davidstutz** [comment]
I think they were from the same algorithm, but these are only examples, so I don't remember fully.
