### ISSUE TITLE
Incompatible licenses?

### ISSUE THREAD

**Issue by rugk** [davidstutz/extended-berkeley-segmentation-benchmark#5]
[Here](https://github.com/davidstutz/extended-berkeley-segmentation-benchmark/blob/master/LICENSE.md) you clearly seem to use the OSI-approved [BSD3-clause license](https://en.wikipedia.org/wiki/BSD_licenses#cite_ref-FSF-ModifiedBSD_6-3).

However in your Readme further down you state that it is licensed under a completely different "non-commercial" license: https://github.com/davidstutz/extended-berkeley-segmentation-benchmark#license

This confuses me and I have no idea what applies. Obviously, the licenses are incompatible/would allow/disallow different usages.

**Comment by davidstutz** [comment]
You are right. I recently needed to update the license and forgot to update the `LICENSE.md` file. Please use the license as stated in the README.
