### ISSUE TITLE
curve plotting

### ISSUE THREAD

**Issue by ZubairKhan001** [davidstutz/extended-berkeley-segmentation-benchmark#6]
can we obtain the precision recall curve instead of small circles using the segmented images as a .mat file.

**Comment by davidstutz** [comment]
You might be able to get a plot using [`plot_eval`](https://github.com/davidstutz/extended-berkeley-segmentation-benchmark/blob/744605b11093a42c01e199be9d6c7e86bc5e2f7c/benchmarks/plot_eval.m) which is provided by the original benchmark. I didn't use it, though, so I can't say how exactly it works.

**Comment by ZubairKhan001** [comment]
Hi, can you please why the ground truth on precision-recall curve has a value of 0.9 and 0.7 for precision and recall respectively, but not 1. Is it because there are 5 ground truth for a single image, each having its own segmentation perspective.  Thanks.

**Comment by davidstutz** [comment]
That might be the reason. But I am not sure exactly. Did you check the paper corresponding to the benchmark/dataset. I remember that the paper discussed the dataset in more detail, so it should include this, as well.

Paper: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/papers/amfm_pami2010.pdf
